print(f"Hello there! Today we have a story about a hungry man. Let's see what happens to him.")
print(f"We have a few qustions for you before the story begins. Don't worry there are no wrong answers!")
print(f"After typing your answers make sure to press the enter key.")
input(f"\nPress the enter key to continue...")
print(f"\nLets answer some questions!")
userName = input("\nWhat is the name of the man?: ")
yogurtType = input("what is the flavor of the yogurt?: ")
pizzaType = input("What kind of pizza does the man have?: ")
manJob = input("Where does the man work?: ")
jobTransport = input("How does the man get to work?: ")
print(f"\nLets get this story started!")
input(f"\nPress the enter key to continue...")
print(f"Our story begins in the very comfy bed of a man named {userName}. ") 
print(f"This morning {userName} is feeling hungry and decides to get out of bed to go to the kitchen. ")
print(f"In the kitchen {userName} opens the fridge and sees some {yogurtType} yogurt. ")
print(f"In the fridge is also some {pizzaType} pizza from the night before. ")
print(f"His phone starts ringing. It's his alarm for work! Oh no he is going to be late for his job at {manJob}! ")
print(f"{userName} heads towards the {jobTransport} to head to work. ")